name: Mobile Optimize Dillinger HTML

on:
  push:
    paths:
      - "docs/**/*.html"  # Triggers only when an HTML file is added/modified in docs/
  workflow_dispatch:  # Allows manual triggering

jobs:
  optimize-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Run mobile optimization script
        run: |
          mkdir -p docs/mobile
          python .github/scripts/process_html.py

      - name: Commit optimized HTML files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/mobile/
          git commit -m "Automated: Mobile optimized Dillinger HTML"
          git push

